### ISSUE TITLE
something wrong with 9.16

### ISSUE THREAD

**Issue by chenyjie** [ensoulsharp-io/EnsoulSharp.Dependencies#18]
[EnsoulSharp]: EnsoulSharp (9.16.284.8446 - 08:45:14 Aug 21 2019) loading...

========================================
Exception occured! EnsoulSharp might crash!

Type: System.ArgumentException
Message: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.

Stracktrace:
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.ToArray()
   at EnsoulSharp.ObjectManager.?????????????????????????????????????????(GameObject , EventArgs )
   at EnsoulSharp.GameObject.?????????????????????????????????????????(?????????????????????????????????????????* )
========================================

it seems that it can't work

And league of legends.exe get stuck

**Comment by qwe522110** [comment]
CN 已更新 可否尽快更新版本？
